contract: ## Build contract
	@RUSTFLAGS="-C link-args=-zstack-size=65536" \
	cargo build \
	  --release \
	  --manifest-path=contract/Cargo.toml \
	  --color=always \
	  -Z build-std=core,alloc \
	  --target wasm32-unknown-unknown
	@mkdir -p target/stripped
	@find target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm" \
	    | xargs -I % basename % \
	    | xargs -I % wasm-tools strip -a \
	 	          target/wasm32-unknown-unknown/release/% \
	 	          -o target/stripped/%

data-driver: ## Build data-driver (generated by #[contract] macro)
	@cargo build \
	  --release \
	  --manifest-path=contract/Cargo.toml \
	  --color=always \
	  --target wasm32-unknown-unknown \
	  --no-default-features \
	  --features data-driver
	@mkdir -p target/stripped
	@cp target/wasm32-unknown-unknown/release/contract.wasm target/stripped/data_driver.wasm
	@wasm-tools strip -a target/stripped/data_driver.wasm -o target/stripped/data_driver.wasm
	@echo "Data-driver WASM: target/stripped/data_driver.wasm"

test: contract ## Run all tests
	@cargo test \
	  --manifest-path=tests/Cargo.toml \
	  --all-features \
	  --color=always
	@cargo test \
	  --manifest-path=dario_fsm/Cargo.toml \
	  --color=always

MAX_COUNTER_CONTRACT_SIZE = 8192

.PHONY: contract data-driver test