contract: ## Build contract
	@RUSTFLAGS="-C link-args=-zstack-size=65536" \
	cargo build \
	  --release \
	  --manifest-path=contract/Cargo.toml \
	  --color=always \
	  -Z build-std=core,alloc \
	  --target wasm32-unknown-unknown \
	  --features contract
	@mkdir -p target/stripped
	@find target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm" \
	    | xargs -I % basename % \
	    | xargs -I % wasm-tools strip -a \
	 	          target/wasm32-unknown-unknown/release/% \
	 	          -o target/stripped/%

moonlight-router: ## Build test-only Moonlight router
	@RUSTFLAGS="-C link-args=-zstack-size=65536" \
	cargo build \
	  --release \
	  --manifest-path=moonlight_router/Cargo.toml \
	  --color=always \
	  -Z build-std=core,alloc \
	  --target wasm32-unknown-unknown \
	  --features contract
	@mkdir -p target/stripped
	@wasm-tools strip -a \
	  target/wasm32-unknown-unknown/release/moonlight_router.wasm \
	  -o target/stripped/moonlight_router.wasm

data-driver: ## Build data-driver (generated by #[contract] macro)
	@cargo build \
	  --release \
	  --manifest-path=contract/Cargo.toml \
	  --color=always \
	  --target wasm32-unknown-unknown \
	  --features data-driver-js
	@mkdir -p target/stripped
	@cp target/wasm32-unknown-unknown/release/contract.wasm target/stripped/data_driver.wasm
	@wasm-tools strip -a target/stripped/data_driver.wasm -o target/stripped/data_driver.wasm
	@echo "Data-driver WASM: target/stripped/data_driver.wasm"

web-assets: data-driver ## Copy generated data-driver into the web app
	@npm --prefix web run prepare:driver

web: web-assets ## Run the web app locally
	@npm --prefix web install
	@npm --prefix web run dev

web-build: web-assets ## Build the web app
	@npm --prefix web ci
	@npm --prefix web run build

test: contract moonlight-router ## Run all tests
	@cargo test \
	  --manifest-path=tests/Cargo.toml \
	  --all-features \
	  --color=always
	@cargo test \
	  --manifest-path=dario_fsm/Cargo.toml \
	  --color=always

.PHONY: contract moonlight-router data-driver web-assets web web-build test
