contract: ## Build contract
	@RUSTFLAGS="-C link-args=-zstack-size=65536" \
	cargo build \
	  --release \
	  --manifest-path=contract/Cargo.toml \
	  --color=always \
	  -Z build-std=core,alloc \
	  --target wasm32-unknown-unknown \
	  --features contract
	@mkdir -p target/stripped
	@find target/wasm32-unknown-unknown/release -maxdepth 1 -name "*.wasm" \
	    | xargs -I % basename % \
	    | xargs -I % wasm-tools strip -a \
	 	          target/wasm32-unknown-unknown/release/% \
	 	          -o target/stripped/%

moonlight-router: ## Build test-only Moonlight router
	@RUSTFLAGS="-C link-args=-zstack-size=65536" \
	cargo build \
	  --release \
	  --manifest-path=moonlight_router/Cargo.toml \
	  --color=always \
	  -Z build-std=core,alloc \
	  --target wasm32-unknown-unknown \
	  --features contract
	@mkdir -p target/stripped
	@wasm-tools strip -a \
	  target/wasm32-unknown-unknown/release/moonlight_router.wasm \
	  -o target/stripped/moonlight_router.wasm

data-driver: ## Build data-driver (generated by #[contract] macro)
	@cargo build \
	  --release \
	  --manifest-path=contract/Cargo.toml \
	  --color=always \
	  --target wasm32-unknown-unknown \
	  --features data-driver-js
	@mkdir -p target/stripped
	@cp target/wasm32-unknown-unknown/release/contract.wasm target/stripped/data_driver.wasm
	@wasm-tools strip -a target/stripped/data_driver.wasm -o target/stripped/data_driver.wasm
	@echo "Data-driver WASM: target/stripped/data_driver.wasm"

web-assets: data-driver ## Copy generated data-driver into the web app
	@npm --prefix web run prepare:driver

zk-assets: ## Copy circom circuit wasm + proving key into the web app
	@mkdir -p web/public/zk
	@cp zk_browser/build/dash/dash_zk_js/dash_zk.wasm web/public/zk/dash_zk.wasm
	@cp zk_browser/build/dash/dash_zk_final.zkey web/public/zk/dash_zk_final.zkey
	@echo "ZK artifacts copied to web/public/zk/"

zk-browser-setup: ## Compile the circom circuit and run Groth16 setup (needs circom; downloads ~300MB ptau once)
	@cd zk_browser && npm install
	@mkdir -p zk_browser/build/dash zk_browser/ptau
	@test -f zk_browser/ptau/powersOfTau28_hez_final_19.ptau || \
	  curl -L -o zk_browser/ptau/powersOfTau28_hez_final_19.ptau \
	    https://storage.googleapis.com/zkevm/ptau/powersOfTau28_hez_final_19.ptau
	@cd zk_browser && circom circuits/dash_zk.circom --r1cs --wasm -o build/dash -l node_modules
	@cd zk_browser && node --max-old-space-size=8192 node_modules/.bin/snarkjs groth16 setup \
	  build/dash/dash_zk.r1cs ptau/powersOfTau28_hez_final_19.ptau build/dash/dash_zk_0000.zkey
	@cd zk_browser && node node_modules/.bin/snarkjs zkey contribute \
	  build/dash/dash_zk_0000.zkey build/dash/dash_zk_final.zkey --name="dario" -e="dario dash entropy"
	@cd zk_browser && node node_modules/.bin/snarkjs zkey export verificationkey \
	  build/dash/dash_zk_final.zkey build/dash/vkey.json
	@cd zk && cargo run --release -p dash-prover -- export-snarkjs-vkey \
	  ../zk_browser/build/dash/vkey.json ../contract/assets dash_zk
	@echo "Circuit + keys ready. Run 'make zk-assets' and rebuild the contract."

dash-web: ## Build the deterministic sim to wasm for the web app
	@wasm-pack build dash_web \
	  --target web \
	  --release \
	  --no-typescript \
	  --out-dir ../web/src/dash-wasm

web: web-assets dash-web ## Run the web app locally
	@npm --prefix web install
	@npm --prefix web run dev

web-build: web-assets dash-web ## Build the web app
	@npm --prefix web ci
	@npm --prefix web run build

zk: ## Build the RISC Zero guest and prover CLI (separate workspace)
	@cd zk && cargo build --release

zk-constants: zk ## Regenerate contract verification constants from the guest
	@cd zk && ./target/release/dash-prover export-constants ../contract/assets

# Usage: make prove RUN=run.json OUT=bundle.json
prove: zk ## Prove a recorded run (requires x86 + Docker for Groth16 wrap)
	@cd zk && ./target/release/dash-prover prove $(abspath $(RUN)) $(abspath $(OUT))

test: contract moonlight-router ## Run all tests
	@cargo test \
	  --manifest-path=tests/Cargo.toml \
	  --all-features \
	  --color=always
	@cargo test \
	  --manifest-path=dario_fsm/Cargo.toml \
	  --color=always
	@cargo test \
	  --manifest-path=dash_core/Cargo.toml \
	  --color=always
	@cargo test \
	  --manifest-path=dash_zk/Cargo.toml \
	  --color=always

.PHONY: contract moonlight-router data-driver web-assets zk-assets zk-browser-setup dash-web web web-build zk zk-constants prove test
