//! # Dario FSM contract
//!
//! This contract is a simple implementation of a Finite-State Machine (FSM) using the Dario FSM library.
//! It manages the state of Dario in a blockchain context, and provides a function to read the state and handle events.
//!
//! This contract uses the `#[contract]` macro from `dusk-wasm` to auto-generate
//! extern wrappers, schema, and data-driver implementations.
#![no_std]

extern crate alloc;

use dusk_forge::contract;

/// The DarioFSM contract module.
///
/// The `#[contract]` macro generates:
/// - Static `STATE` variable with the contract struct
/// - Extern "C" wrapper functions for WASM export
/// - `CONTRACT_SCHEMA` constant with metadata
/// - `data_driver` module when compiled with the `data-driver` feature
#[contract]
mod dario_fsm_contract {
    use alloc::collections::{BTreeMap, BTreeSet};
    use alloc::string::String;
    use alloc::vec::Vec;

    // Import the Dario FSM library
    use dario_fsm::{transition, DarioState, Event};
    // Import Dusk Core functionality, primarily for making calls and emitting events
    use ark_ff::PrimeField;
    use dusk_bytes::Serializable;
    use dusk_core::groth16::bn254::{Fr, G1Projective};
    use dusk_core::groth16::serialize::{CanonicalDeserialize, CanonicalSerialize};
    use dusk_core::signatures::bls::PublicKey;
    use dusk_core::transfer::TRANSFER_CONTRACT;
    use dusk_core::{self, abi};
    use sha2::{Digest as _, Sha256};

    const ACCOUNT_KEY_BYTES: usize = 193;
    type AccountKey = [u8; ACCOUNT_KEY_BYTES];

    /// Compressed BLS public account bytes, as committed in the ZK journal.
    const ACCOUNT_BYTES: usize = PublicKey::SIZE; // 96
    type Account = [u8; ACCOUNT_BYTES];

    // RISC Zero Groth16 verification constants, generated by
    // `zk/prover export-constants`.
    /// ark 0.4 `PreparedVerifyingKey<Bn254>`, uncompressed.
    const PVK: &[u8] = include_bytes!("../assets/pvk.bin");
    /// The 6 `gamma_abc_g1` points (uncompressed G1, 64 bytes each).
    const GAMMA_ABC: &[u8] = include_bytes!("../assets/gamma_abc.bin");
    /// Image ID of the dash guest program.
    const IMAGE_ID: &[u8; 32] = include_bytes!("../assets/image_id.bin");
    /// RISC Zero allowed control root.
    const CONTROL_ROOT: &[u8; 32] = include_bytes!("../assets/control_root.bin");
    /// RISC Zero BN254 identity control ID.
    const BN254_CONTROL_ID: &[u8; 32] = include_bytes!("../assets/bn254_control_id.bin");

    // Browser (circom/snarkjs) circuit verification constants, generated by
    // `zk/prover export-snarkjs-vkey`.
    /// ark 0.4 `PreparedVerifyingKey<Bn254>` for the dash_zk circuit.
    const ZK_PVK: &[u8] = include_bytes!("../assets/dash_zk_pvk.bin");
    /// The 636 `gamma_abc_g1` points of the dash_zk circuit.
    const ZK_GAMMA_ABC: &[u8] = include_bytes!("../assets/dash_zk_gamma_abc.bin");
    /// Number of public inputs of the dash_zk circuit.
    const ZK_N_PUBLIC: usize = 635;

    const JOURNAL_LEN: usize = ACCOUNT_BYTES + 8 + 8 + 4;

    #[derive(Clone, Copy)]
    struct PlayerState {
        current_state: DarioState,
        revive_count: u32,
    }

    impl PlayerState {
        const fn new() -> Self {
            Self {
                current_state: DarioState::Regular,
                revive_count: 0,
            }
        }

        fn current_state(&self) -> u32 {
            self.current_state as u32
        }

        fn handle_event(&mut self, event: Event) {
            let previous_state = self.current_state;
            let new_state = transition(self.current_state, event);

            if previous_state == DarioState::GameOver && event == Event::Revive {
                self.revive_count = self.revive_count.saturating_add(1);
            }

            self.current_state = new_state;
        }
    }

    #[derive(Clone, Copy)]
    struct ProvenStats {
        best_score: u64,
        runs: u32,
        total_ticks: u64,
    }

    /// The DarioFSM struct describes how the state for this contract looks like
    /// There should only be one public struct
    pub struct DarioFSM {
        current_state: DarioState,
        revive_count: u32,
        players: BTreeMap<AccountKey, PlayerState>,
        proven: BTreeMap<Account, ProvenStats>,
        used_seeds: BTreeSet<(Account, u64)>,
    }

    impl DarioFSM {
        /// Creates a new DarioFSM instance with initial state Regular.
        pub const fn new() -> Self {
            Self {
                current_state: DarioState::Regular,
                revive_count: 0,
                players: BTreeMap::new(),
                proven: BTreeMap::new(),
                used_seeds: BTreeSet::new(),
            }
        }

        /// Returns the current caller-scoped state as a u32.
        ///
        /// Moonlight calls routed through the transfer contract read the
        /// public sender's state. Direct VM calls retain the original global
        /// state so local tests and simple read-only calls remain compatible.
        pub fn current_state(&self) -> u32 {
            if let Some(account) = moonlight_sender() {
                return self
                    .players
                    .get(&account)
                    .map(PlayerState::current_state)
                    .unwrap_or(DarioState::Regular as u32);
            }

            self.current_state as u32
        }

        /// Returns the current caller-scoped revive count.
        pub fn revive_count(&self) -> u32 {
            if let Some(account) = moonlight_sender() {
                return self
                    .players
                    .get(&account)
                    .map(|state| state.revive_count)
                    .unwrap_or(0);
            }

            self.revive_count
        }

        /// Returns a Moonlight public account's current Dario state.
        pub fn current_state_for(&self, account: String) -> u32 {
            let account = account_key_from_address(account);

            self.players
                .get(&account)
                .map(PlayerState::current_state)
                .unwrap_or(DarioState::Regular as u32)
        }

        /// Returns a Moonlight public account's revive count.
        pub fn revive_count_for(&self, account: String) -> u32 {
            let account = account_key_from_address(account);

            self.players
                .get(&account)
                .map(|state| state.revive_count)
                .unwrap_or(0)
        }

        /// Handles a game event and updates Dario's state accordingly
        ///
        /// # Arguments
        ///
        /// * `Event` - A `u32` corresponding to the `Event` enum
        pub fn handle_event(&mut self, event: u32) {
            let event = Event::try_from(event).expect("Invalid event number passed");

            if let Some(account) = moonlight_sender() {
                let state = self.players.entry(account).or_insert_with(PlayerState::new);
                state.handle_event(event);
                dusk_core::abi::emit("state", state.current_state as u32);
                return;
            }

            let previous_state = self.current_state;
            let new_state = transition(self.current_state, event);

            if previous_state == DarioState::GameOver && event == Event::Revive {
                self.revive_count = self.revive_count.saturating_add(1);
            }

            self.current_state = new_state;
            dusk_core::abi::emit("state", self.current_state as u32);
        }

        /// Submits a ZK-proven game run.
        ///
        /// The proof is a RISC Zero Groth16 receipt (converted to an ark 0.4
        /// compressed `Proof<Bn254>`, 128 bytes) attesting that the dash guest
        /// program replayed an input trace for `seed` and produced exactly
        /// `score` over `ticks` ticks, for the calling Moonlight account.
        ///
        /// Panics if the caller is not a Moonlight transaction, the seed was
        /// already used by this account, the score exceeds the ranked cap, or
        /// the proof does not verify.
        pub fn submit_run(&mut self, seed: u64, score: u64, ticks: u32, proof: Vec<u8>) {
            let pk = moonlight_public_key()
                .expect("submit_run must be called directly via a Moonlight transaction");
            let account: Account = pk.to_bytes();

            assert!(score <= dash_zk::MAX_RANKED_SCORE, "score out of range");

            assert!(
                self.used_seeds.insert((account, seed)),
                "seed already used by this account"
            );

            // Reconstruct the exact journal the guest committed.
            let mut journal = [0u8; JOURNAL_LEN];
            journal[..ACCOUNT_BYTES].copy_from_slice(&account);
            journal[ACCOUNT_BYTES..ACCOUNT_BYTES + 8].copy_from_slice(&seed.to_le_bytes());
            journal[ACCOUNT_BYTES + 8..ACCOUNT_BYTES + 16].copy_from_slice(&score.to_le_bytes());
            journal[ACCOUNT_BYTES + 16..].copy_from_slice(&ticks.to_le_bytes());

            let claim = claim_digest(&journal);
            let prepared = prepared_public_inputs(&claim);

            assert!(
                abi::verify_groth16_bn254(PVK.to_vec(), proof, prepared),
                "invalid gameplay proof"
            );

            let stats = self.proven.entry(account).or_insert(ProvenStats {
                best_score: 0,
                runs: 0,
                total_ticks: 0,
            });
            stats.best_score = stats.best_score.max(score);
            stats.runs = stats.runs.saturating_add(1);
            stats.total_ticks = stats.total_ticks.saturating_add(ticks as u64);

            dusk_core::abi::emit("run", score);
        }

        /// Submits a browser-proven game run (circom/snarkjs Groth16-BN254).
        ///
        /// The proof attests that a valid 30 Hz Dash run over the obstacle
        /// schedule derived from `seed` scored exactly `score` in `ticks`
        /// ticks. The contract recomputes the schedule natively from `seed`
        /// and binds the caller's Moonlight account into the public inputs,
        /// so the proof cannot be replayed by anyone else.
        ///
        /// Panics if the caller is not a Moonlight transaction, the seed was
        /// already used by this account, `score`/`ticks` are out of range, or
        /// the proof does not verify.
        pub fn submit_zk_run(&mut self, seed: u64, score: u64, ticks: u32, proof: Vec<u8>) {
            let pk = moonlight_public_key()
                .expect("submit_zk_run must be called directly via a Moonlight transaction");
            let account: Account = pk.to_bytes();

            assert!(
                self.used_seeds.insert((account, seed)),
                "seed already used by this account"
            );

            // The circuit assumes the contract enforces public-input ranges.
            assert!(
                (1..=dash_zk::MAX_TICKS).contains(&ticks),
                "ticks out of range"
            );
            assert!(score <= dash_zk::MAX_RANKED_SCORE, "score out of range");

            let inputs = zk_public_inputs(seed, score, ticks, &account);
            let prepared = prepare_inputs(ZK_GAMMA_ABC, &inputs);

            assert!(
                abi::verify_groth16_bn254(ZK_PVK.to_vec(), proof, prepared),
                "invalid gameplay proof"
            );

            let stats = self.proven.entry(account).or_insert(ProvenStats {
                best_score: 0,
                runs: 0,
                total_ticks: 0,
            });
            stats.best_score = stats.best_score.max(score);
            stats.runs = stats.runs.saturating_add(1);
            stats.total_ticks = stats.total_ticks.saturating_add(ticks as u64);

            dusk_core::abi::emit("zk_run", score);
        }

        /// Returns a Moonlight account's best proven score.
        pub fn best_score_for(&self, account: String) -> u64 {
            self.proven
                .get(&account_from_address(account))
                .map(|s| s.best_score)
                .unwrap_or(0)
        }

        /// Returns a Moonlight account's number of proven runs.
        pub fn proven_runs_for(&self, account: String) -> u32 {
            self.proven
                .get(&account_from_address(account))
                .map(|s| s.runs)
                .unwrap_or(0)
        }

        /// Returns the top 10 proven scores as (account, best_score, runs),
        /// sorted by best score descending.
        pub fn leaderboard(&self) -> Vec<(String, u64, u32)> {
            let mut entries: Vec<_> = self
                .proven
                .iter()
                .map(|(account, s)| (bs58::encode(account).into_string(), s.best_score, s.runs))
                .collect();
            entries.sort_by_key(|entry| core::cmp::Reverse(entry.1));
            entries.truncate(10);
            entries
        }
    }

    impl Default for DarioFSM {
        fn default() -> Self {
            Self::new()
        }
    }

    fn moonlight_sender() -> Option<AccountKey> {
        moonlight_public_key().map(|pk| pk.to_raw_bytes())
    }

    fn moonlight_public_key() -> Option<PublicKey> {
        let caller = abi::caller();
        let callstack_len = abi::callstack().len();

        if matches!(caller, Some(TRANSFER_CONTRACT)) && callstack_len <= 1 {
            abi::public_sender()
        } else {
            None
        }
    }

    fn account_key_from_address(account: String) -> AccountKey {
        let bytes = bs58::decode(account)
            .into_vec()
            .expect("Invalid Moonlight account encoding");
        let bytes: [u8; PublicKey::SIZE] = bytes
            .try_into()
            .unwrap_or_else(|_| panic!("Moonlight account must be a public account"));
        let key = PublicKey::from_bytes(&bytes).expect("Invalid Moonlight public account");

        key.to_raw_bytes()
    }

    fn account_from_address(account: String) -> Account {
        let bytes = bs58::decode(account)
            .into_vec()
            .expect("Invalid Moonlight account encoding");
        bytes
            .try_into()
            .unwrap_or_else(|_| panic!("Moonlight account must be a public account"))
    }

    // --- RISC Zero Groth16 verification (ported from risc0 3.0.5) ---

    /// `tagged_struct` hash from risc0-binfmt:
    /// sha256(sha256(tag) || down digests || data words LE || down count u16 LE).
    fn tagged_struct(tag: &str, down: &[&[u8; 32]], data: &[u32]) -> [u8; 32] {
        let mut h = Sha256::new();
        h.update(Sha256::digest(tag.as_bytes()));
        for digest in down {
            h.update(&digest[..]);
        }
        for word in data {
            h.update(word.to_le_bytes());
        }
        h.update((down.len() as u16).to_le_bytes());
        h.finalize().into()
    }

    /// Digest of `ReceiptClaim::ok(IMAGE_ID, journal)`: a normally-halted
    /// execution of the dash guest that committed exactly `journal`.
    fn claim_digest(journal: &[u8]) -> [u8; 32] {
        const ZERO: [u8; 32] = [0u8; 32];

        let journal_digest: [u8; 32] = Sha256::digest(journal).into();
        let output = tagged_struct("risc0.Output", &[&journal_digest, &ZERO], &[]);
        let post = tagged_struct("risc0.SystemState", &[&ZERO], &[0]);

        tagged_struct(
            "risc0.ReceiptClaim",
            &[&ZERO, IMAGE_ID, &post, &output],
            &[0, 0], // ExitCode::Halted(0)
        )
    }

    /// Computes the prepared public inputs (32-byte compressed G1) expected
    /// by `verify_groth16_bn254`: `gamma_abc[0] + sum(inputs[i] * gamma_abc[i+1])`.
    /// `gamma_abc` holds uncompressed G1 points (64 bytes each).
    fn prepare_inputs(gamma_abc: &[u8], inputs: &[Fr]) -> Vec<u8> {
        let mut points = gamma_abc.chunks_exact(64).map(|chunk| {
            G1Projective::deserialize_uncompressed_unchecked(chunk)
                .expect("gamma_abc asset must hold valid G1 points")
        });
        let mut acc = points.next().expect("gamma_abc asset must not be empty");
        for input in inputs {
            let point = points
                .next()
                .expect("gamma_abc asset must hold nPublic + 1 points");
            acc += point * input;
        }

        let mut out = Vec::with_capacity(32);
        acc.serialize_compressed(&mut out)
            .expect("serializing prepared inputs cannot fail");
        out
    }

    /// Builds the 635 dash_zk circuit public inputs, in circuit order:
    /// score, ticks, groundCount, batCount, itemCount, gspawn/gw/gh[128],
    /// bspawn/bbase/bphase[24], ispawn/ikind/iy[56], acct[6].
    ///
    /// The schedule is recomputed natively from `seed` — the exact same
    /// no_std code the browser simulation runs — so a proof only verifies
    /// against the true obstacle timeline for that seed.
    fn zk_public_inputs(seed: u64, score: u64, ticks: u32, account: &Account) -> Vec<Fr> {
        use dash_zk::{Schedule, MAX_BATS, MAX_GROUND, MAX_SCHED_ITEMS};

        let sched = Schedule::generate(seed);

        let mut inputs = Vec::with_capacity(ZK_N_PUBLIC);
        inputs.push(Fr::from(score));
        inputs.push(Fr::from(ticks));
        inputs.push(Fr::from(sched.ground_count as u64));
        inputs.push(Fr::from(sched.bat_count as u64));
        inputs.push(Fr::from(sched.item_count as u64));
        for i in 0..MAX_GROUND {
            inputs.push(Fr::from(sched.ground[i].spawn_tick));
        }
        for i in 0..MAX_GROUND {
            inputs.push(Fr::from(sched.ground[i].w as u64));
        }
        for i in 0..MAX_GROUND {
            inputs.push(Fr::from(sched.ground[i].h as u64));
        }
        for i in 0..MAX_BATS {
            inputs.push(Fr::from(sched.bats[i].spawn_tick));
        }
        for i in 0..MAX_BATS {
            inputs.push(Fr::from(sched.bats[i].base_y_px as u64));
        }
        for i in 0..MAX_BATS {
            inputs.push(Fr::from(sched.bats[i].phase0));
        }
        for i in 0..MAX_SCHED_ITEMS {
            inputs.push(Fr::from(sched.items[i].spawn_tick));
        }
        for i in 0..MAX_SCHED_ITEMS {
            inputs.push(Fr::from(sched.items[i].kind as u64));
        }
        for i in 0..MAX_SCHED_ITEMS {
            inputs.push(Fr::from(sched.items[i].y_px as u64));
        }
        // Account limbs: 96 bytes as 6 little-endian u128 limbs.
        for limb in account.chunks_exact(16) {
            let mut bytes = [0u8; 16];
            bytes.copy_from_slice(limb);
            inputs.push(Fr::from(u128::from_le_bytes(bytes)));
        }
        debug_assert_eq!(inputs.len(), ZK_N_PUBLIC);
        inputs
    }

    /// Computes the prepared public inputs for the RISC Zero receipt:
    /// the 5 Fr inputs [control_root split, claim split, bn254 id].
    fn prepared_public_inputs(claim: &[u8; 32]) -> Vec<u8> {
        let inputs: [Fr; 5] = [
            Fr::from_le_bytes_mod_order(&CONTROL_ROOT[0..16]),
            Fr::from_le_bytes_mod_order(&CONTROL_ROOT[16..32]),
            Fr::from_le_bytes_mod_order(&claim[0..16]),
            Fr::from_le_bytes_mod_order(&claim[16..32]),
            Fr::from_le_bytes_mod_order(&BN254_CONTROL_ID[..]),
        ];
        prepare_inputs(GAMMA_ABC, &inputs)
    }
}
